### PR TITLE
Documentation for worker workaround on Windows

### PR DESCRIPTION
**Pull request by Hemaolle**
Describe how to start workers manually if they are not automatically
started on Windows.

Thought these instructions might be useful.

### CODE REVIEW

**Comment by daveyarwood** [comment]
Looks good to me, thank you! 👍

**Comment by daveyarwood** [comment]
@Hemaolle Since https://github.com/alda-lang/alda-core/issues/31 was resolved, I think we might want to revert this documentation change. I'm concerned that it makes Alda Windows support look spotty. What do you think?

**Comment by Hemaolle** [comment]
@daveyarwood, of course!

**Comment by daveyarwood** [comment]
OK, cool. I'll revert it on master. :+1:

**Pull request merged**
