### PR TITLE
Fix requirements names

### PR DESCRIPTION
**Pull request by 0atman**
Seem to be an extra "alda" in the name here, I had to remove it to get it to work in my project.clj

### CODE REVIEW

**Comment by 0atman** [comment]
No problem! I'm telling everyone at Clojure eXchange (london) about alda!

**Comment by daveyarwood** [comment]
Awesome! Thanks for spreading the word! 😄

**Comment by daveyarwood** [comment]
@0atman I recommend mentioning this demo to Clojure folks: https://www.youtube.com/watch?v=c5pCFtwO4j8

It's a demo I gave at ICFP (an academic functional programming conference) last year where I talked about using functional programming to make music. I live-coded an Alda score, and used a lot of inline Clojure code, so it's also a nice demo of the Alda Clojure DSL.

**Comment by 0atman** [comment]
ooh, nice - will do!

**Pull request merged**
