### PR TITLE
Place octave-(up/down) directly into grammar

### PR DESCRIPTION
**Pull request by crisptrutski**
Noticed something simple, and decided to dip my toes in :swimmer: :smile: 

Refs #59

### CODE REVIEW

**Comment by crisptrutski** [comment]
Niggly point on your naming scheme for test namespaces: can't use CIDER commands because it expects `-test` suffix in the namespace name (otherwise assumes you're calling from namespace-under-test, and fails trying to reload the namespace with suffix added)

Being finite in my bravery, I haven't checked whether I can change/configure things on the CIDER side. Would you object to a PR renaming the namespaces and updating the test task, for my creature comfort?

**Comment by daveyarwood** [comment]
Looks good - awesome first PR, thanks!

I'm going to make a small change before merging -- using the `#(list ...` format in alda.parser instead of `(constantly (list ...` for the sake of consistency.

I don't have a particular reason for the current test namespace scheme -- would happily accept a PR rearranging them for the benefit of CIDER users.

**Comment by crisptrutski** [comment]
One different with the `constantly` version is that it's a bit more memory friendly (shares that immutable data), and to split hairs you do use that form a bit above (although for a different group) :smile: 

Thanks for the flexibility, I just might make that change the next time I update any tests

**Comment by daveyarwood** [comment]
Aha - I didn't know that. Maybe we should change them all to `(constantly '(alda.lisp/...` for a minor perf boost.

**Comment by crisptrutski** [comment]
Can only use it for the cases that don't take any parameters - but I'm cool either way. Reached for `constantly` before I figured out that `<...>` could stop the arguments being passed (creating anonymous functions that ignore their inputs isn't that pretty)

**Pull request merged**
